apiVersion: ENC[AES256_GCM,data:DvM=,iv:wYZDTz4HqZaL3jex03fDDQ1WLqaeSKzRFbQaP8UN1fE=,tag:SLxAu24m+zjx9SLiE9+Stg==,type:str]
kind: ENC[AES256_GCM,data:a6HjHETe,iv:7uqzGDLEKWtIalIBkyGFVRvUla6ly4L42x3Y0e9F5YU=,tag:rk1jcqOOmFqR8yGlIsCp1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jy5YWggGcXeOZpAVWlGf8W/I3TU=,iv:tYNIol22U0k31OtVQw5wGg8E9aUDSHcJlpuFAeuE6UY=,tag:ME6A4wicCoucYqJ8ym6aow==,type:str]
type: ENC[AES256_GCM,data:Wvk0JF7H,iv:4p67UZgwr59g67T+DFxzETe4HSol3xZC0i/iIyP8wAI=,tag:iQX5NEjvS6XL+z3g+1h/ww==,type:str]
data:
    jwt.secret: ENC[AES256_GCM,data:QyolcNIZ0++F1Ga3Xr1wjTLW2/0ZO3v0BlxHcsp95asPp1Dy4N38IyyVHhucMxgSOjYCR4MRSOZwUqMKqK4O0nD8FGjETegYHI7CsTzDLA1pGBk83V+WSQ==,iv:I3GXRp0NKf14voiuxRhkJWHC2SOPlRzk+CddgBZoPms=,tag:TzEl/NwXeSBGqmTXpTNCDA==,type:str]
sops:
    age:
        - recipient: age10208829zx6nejmh0xdrcg2m37ld2lcnx4farmurfel7w5g8g6q7sjpva60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ekhac09BVVVpeTdEMFg2
            OGxnS0NxTWhhOGU3L1FUMS9OclRwL1ZIL1Y4CjdSUjNFK0dHSEpMSmt4QUhob1V1
            Z2JOdHJhK1ZSZ0VhQzlBallSenVxY1EKLS0tIGZTQUJISDRjODBGZGl2bGNkRTRF
            c1BjSGFoMnBwcHNpeWpFVGtNZlB1V0UKrpiHeBgCdgpLz2g8tmK2ubaT/kWjxVG3
            KBs8fPl2g5P67d77/Y83OKbkDmsmmNEUNE66q3kxW0LuwYDhI02lCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T14:45:17Z"
    mac: ENC[AES256_GCM,data:IILtzCw8Xit2RHO+CJ2+RM++uPr+7i7k2YbocsysmA/0+3uKAx6HBlNT41fjXeTpi9HIGDALpPJW/AwpD1MGVi5C2ZtGN0SlK1fTGXb49vtGPdV9263YAVMTkwT5i9QgtNWY7sEEpkZdqLzJfH8ApAWtsbZAEtxnObyYY+G4RNI=,iv:mGDPLjb715Dy2wKWX15RGspGlylL/WpkpbaUKbO3Chc=,tag:cpJbjuqOL59WaOid5VTPmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
