apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int-snaptrail

resources:
  - ../../base
  - ingress.yaml
  - namespace.yaml
  - db-credentials.dec.yaml
  - admin-credentials.dec.yaml
  - jwt-secret.dec.yaml
