apiVersion: apps/v1
kind: Deployment
metadata:
  name: snaptrail-deployment
  labels:
    app: snaptrail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snaptrail
  template:
    metadata:
      labels:
        app: snaptrail
    spec:
      containers:
        - name: snaptrail
          image: ghcr.io/markusharder/snaptrail:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pg-cert
              mountPath: /certs
          env:
            - name: GIN_MODE
              value: release
            - name: DOMAIN_SUFFIX
              value: .snaptrail.markusharder.com
            - name: DEV
              value: "false"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: snaptrail-jwt-secret
                  key: jwt.secret
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: snaptrail-admin-user-secret
                  key: user.name
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snaptrail-admin-password-secret
                  key: user.password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: snaptrail-db-secret
                  key: database.url
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: s3.access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: s3.secret_key
          envFrom:
            - configMapRef:
                name: s3-config
          livenessProbe:
            httpGet:
              path: /admin
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 8115
              name: "web"
            - containerPort: 8000
              name: "admin"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: pg-cert
          secret:
            secretName: TO_REPLACE
