apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - svc.yaml
  - pdp.yaml
  - pull-secret.dec.yaml
  - s3-credentials.dec.yaml
  - s3-env.yaml

secretGenerator:
  - name: pg-cert
    files:
      - ./secrets/pg-cert/ca.dec.crt
    type: Opaque

replacements:
  - source:
      kind: Secret
      name: pg-cert
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: snaptrail-deployment
        fieldPaths:
          - spec.template.spec.volumes.[name=pg-cert].secret.secretName
