apiVersion: ENC[AES256_GCM,data:rBU=,iv:EFVFnyJ6PxMloNbPPXkxjWxJZkCc2jHcbmJ6r4jV/ZA=,tag:D5S8eCiXoeNUOaFZL/ZoEQ==,type:str]
data:
    s3.access_key: ENC[AES256_GCM,data:Zesl9kJt81UGvZW6,iv:9JkqoRVZSo2kL4C0u2bfGDb0vEE1i7uHCAvpTdPzi70=,tag:kZUU/qA5PWJxY4x7h28OZQ==,type:str]
    s3.secret_key: ENC[AES256_GCM,data:jwbvlJyDLdRA+W/GC4GW5xIWCVs=,iv:m7kQF1mE60qGnGKSupGuwqf71qRoe2SUyWQ8yEZkqGQ=,tag:ATeYmZgxUmlR4joUY9LoZg==,type:str]
kind: ENC[AES256_GCM,data:BhOduXIB,iv:4p8rkj6LPfdFd/BcJDJ52ZMSyvzGe8QerQK4Tvubxio=,tag:oN6AKobLdTyxJZDL4897eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k0stKldQCFfBYT2c,iv:deomqCt8WeXrVkoBBEhol6w/lYmsh3+xGmz6uqAO2kc=,tag:GB3+jf3BrvPcDkkKZVGP2w==,type:str]
    namespace: ENC[AES256_GCM,data:Dhem/sL9vryfQQZb,iv:gWlj0Z+RcpewcPYxvQ69pTWidlPyvyeoslvvYR6+NUI=,tag:O9oOynhTEUORMFwTFDPVzg==,type:str]
type: ENC[AES256_GCM,data:PUlUs1A8,iv:b+oeecgXv0cgG/nReBxnLlLD5W0twBH4NCS/dBp8nH8=,tag:dl9B0JFEtJB08o5PN9V8iQ==,type:str]
sops:
    age:
        - recipient: age10208829zx6nejmh0xdrcg2m37ld2lcnx4farmurfel7w5g8g6q7sjpva60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONDFsUkI3a0VzeHhPWkVr
            K2lhRmlHUU5pQnhXTDZvRW9mTGV5TU45cm04CjZacy9uUEx4d1hRS0VORTYwQ09Y
            UTNNNlNYYlZFRDY1M0hZU0pmR3FCRFEKLS0tIHJDMno4VnI5N2NpWERzV01GSnZO
            dkVkY2xrcmc2TGluaGNwbnJqVlp6OE0KraILZCPc8bKuL1UnpvnG2d99zicZttuM
            kavRLytYul9+h3xoDN3koUsOUs+RtdmAYv5ZyEKqql6tR6SzEUTecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T19:06:06Z"
    mac: ENC[AES256_GCM,data:ZQguQUU3tX5HFmFWfxO0Stpc239Hxt1Z24xzbB+hfp/GhogYfmDZ4zTMoi2QBk65Nq6t1Dn5V5Kt2tKRsC/MdCo9VTabLn7/19JfO/2jrt/vczIf8R7wVtp68PXDiu+teT1YJ3thCzLjz7nz+Q0l1QnoD+7j6jvDg4Lv0ZS2QUA=,iv:5bEvbT5U03mQc8325HbbkHTGak1IrASDgRXcnQTh3gY=,tag:TgGz5zLKCcwCdvm9EAAuNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
