apiVersion: ENC[AES256_GCM,data:/IM=,iv:mXobnc4OJqcwRXCUx0hiRFoWNAVPs0t28hi1BPcEM+Q=,tag:WCL601KGr2vYrjJbApiF7A==,type:str]
kind: ENC[AES256_GCM,data:ZesCbyG8,iv:8aC0Ca0SdHb5WeRbQdKMJuI1MfhS6C/kbItp+Z+f4qM=,tag:kP/m0pkca7+F60LaqvDnwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gnp0FL6ectQ9x0jo,iv:5LBvsmB74m5U8TYC3jqJn1JqL5GTLvfZ1Hl5LZ+ISeM=,tag:PV6j6uPO09K3hRVbMZK6JA==,type:str]
type: ENC[AES256_GCM,data:9dTReQPu,iv:GNkX2yWQFsA7a4g3cT6JOpKaFX4tQqwLrwIK0T7jvso=,tag:B/gaQ4ZvMp+ZHSg9N7q7hg==,type:str]
stringData:
    s3.access_key: ENC[AES256_GCM,data:pfzMOytTRk0Qbho6d8oqHU1MuYg=,iv:WTDeobJXM6D2ks85z7wfkJamJzCgEjMYh/wecY6Xs8I=,tag:pT+hWeuOPFd1Y8mcPi0nYw==,type:str]
    s3.secret_key: ENC[AES256_GCM,data:PmCuUF6uzoj3gEVHaJ5R4Z18dNhgKGutF7UfI2HLXbe2G8fG4NXjag==,iv:1OgnWCnGPu3HMVsc5DTPTh7peItZCl+34rPQdwhYJW8=,tag:zRFZE8Md3nN2fckNp3ou+g==,type:str]
sops:
    age:
        - recipient: age10208829zx6nejmh0xdrcg2m37ld2lcnx4farmurfel7w5g8g6q7sjpva60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d3JyVDdGUUEyejdnbUx4
            ZkQ4RUQrbExYdWMvR3d2dXFaMGw1eFR6a2tRCmhEWllsek1BYXFNdXVuYzgwMmhL
            R1JENERHVFdCS0xRT0cxWkxKQldHcEUKLS0tIEJ4TFVROCt5QUk0K2FTUHNKcWxS
            OUdkNkovUlMxNDFKQzhtU3NaaFEzZGMKYsoV6HomQdBI62R3tlx6H2dpHRitUFZ6
            XA6FYJ+9vy9i00ix7Hry5K5iQVt0l5sq2l0TDTVlJ2oqAkYvnRKhUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T13:17:03Z"
    mac: ENC[AES256_GCM,data:xukF9zSNzMLj3yO9Z1/HSM2gjrozpxi+ECPoIzgxDfw2APBiXpZf0eY7f2YejISplCTvA0b885KQnQAyxsKXiH8Gy9bKMm3XzdoGPxBF6Et2QFT9M8aiwomRzuvOLiWSH32nCBHAOKN1rBri0BtlmrfG1yCoOrs63l6qL54j0r4=,iv:EbADs06pu6JX0upQuO7IlHUCNxNT1Wsz6UnJMzNtxRg=,tag:tzBMHOy6h97UALncJ8MPjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
